### PR TITLE
Implement background synchronization

### PR DESCRIPTION
**Pull request by kitlangton**
This resolves issue #88.

I am unable to test this particular branch at the moment, as my personal fork of IceCream includes a few other changes (in order to get IceCream to work with App Groups and to fix some other sync issues. Both of which I will try to extract into PRs in the near future). I tried to extract only the background synchronization implementation. Background synchronization works wonderfully in my own project, so if I've extracted it correctly, it should work here as well.

### CODE REVIEW

**Comment by kitlangton** [comment]
@drmarkpowell @dbmrq 

Could you check if this works for you? (If you're still interested in testing of this PR)

**Comment by dbmrq** [comment]
I just gave it a try and it seems to be working perfectly!

@caiyue1993 Let's merge this! :pray:

**Comment by caiyue1993** [comment]
Hi @kitlangton , the PR looks good. And how about just using GCD to create a custom queue instead of `BackgroundWorker` here?

**Comment by kitlangton** [comment]
@caiyue1993, I'm not sure. I believe that Realm needs a RunLoop to function properly. Would a GCD queue have one of these? I added the blog post I referenced in a comment at the top of the background worker file.

**Comment by dbmrq** [comment]
@caiyue1993 Yeah, from what I gathered, the worker class is necessary to use and keep track of a thread with its own runloop, as described in [that article](https://academy.realm.io/posts/realm-notifications-on-background-threads-with-swift:). I think GCD can't be trusted to use the same runloop every time. Before reading the article I tried using GCD and failed… but that could also be my own incompetence.

**Comment by dbmrq** [comment]
@caiyue1993 Another relevant link: https://stackoverflow.com/a/41841847/3539651

**Comment by kitlangton** [comment]
@donavoncade, I see you have tested out this branch :) . Any luck?

**Comment by donavoncade** [comment]
> @donavoncade, I see you have tested out this branch 😸. Any luck?

It seems to work well except that my app will sometimes crash when registerLocalDatabase() is called on a SyncObject. I haven't been able to figure out exactly what's going on. Looking at the debugger, the crash doesn't actually happen until the app transitions from background to active state.

**Comment by kitlangton** [comment]
@donavoncade, Just to be clear, this error didn’t happen until you pulled in this PR, right?

**Comment by donavoncade** [comment]
> @donavoncade, Just to be clear, this error didn’t happen until you pulled in this PR, right?

That's correct. And reverting back resolves the error. I've gone back and forth a few times just to be sure.

**Comment by donavoncade** [comment]
> @donavoncade, Just to be clear, this error didn’t happen until you pulled in this PR, right?

Decided to try this out again after fixing what seemed to be a different Realm issue with my tableview cells. This crash hasn't occurred since.

**Comment by dbmrq** [comment]
I haven’t tested that throughly, but didn’t get any crashes either so far.

**Comment by limura** [comment]
I hope this pull request solves the problem it is trying to solve.
However, I think this pull request has some problems.

In the SyncEngine, where backgroundWorker.perform is running, the Realm object is generated with no arguments:
https://github.com/caiyue1993/IceCream/pull/132/commits/0d41689901d1a51d8ccf817fc17c024b7fa56a58#diff-2d12a78d6f16cf3f0cae050605195c27R76

This indicates that you are not using Realm objects that may be passed to the SyncEngine or SyncObject initializers.
Indeed, backgroundWorker will not be able to use Realm objects passed to the SyncEngine or SyncObject initializers. The Thread in backgroundWorker.perform is different from the Thread on which the passed Realm object was generated.

However, I want to generate a Realm object with Realm.
Therefore, in addition to the pull request, could Realm.Configuration be passed in place of the Realm object passed to the SyncEngine and SyncObject arguments?

In my application, I want to handle Realm database using IceCream and standalone Realm database without IceCream at the same time, so I think it is impossible to avoid it by rewriting the default configuration of Realm. Therefore, instead of just ignoring the Realm object given as an argument like the current pull request, I want Realm.Configuration to be given as an argument.

**Comment by caiyue1993** [comment]
Hi @limura, you are totally right. I found this problem too when reviewing. Indeed we should not force the outside Realm(just like in your application) to be generated in the same thread as the thread as the backgroundWorker's.
Passing Realm.Configuration as an argument is a great idea and we'll definitely try it in this pull request. Thank you so much and please help us to test when finished.

**Pull request closed without merging**
