### PR TITLE
Add basic sharing capability

### PR DESCRIPTION
**Pull request by rodericj**
re #4

### CODE REVIEW

**Comment by Filippopotamus** [comment]
Any news on this? :)

**Comment by rodericj** [comment]
@filippopotamus did you try getting it working? We had a bit of a golden path working but got sidetracked with shipping out MVP. It’s on our short roadmap to jump back into it

**Comment by joeljfischer** [comment]
@rodericj I've been working on getting it working in an example app I have using IceCream. The lack of usage documentation is making it a bit rough as I'm not exactly sure when to alter my `databaseType` from private to shared, for example. There were also a few corrections to be made in order to compile.

**Comment by joeljfischer** [comment]
Other sticking points include using `databaseType` within the Realm `Object`, when that data should be set and how.

**Comment by Filippopotamus** [comment]
Sorry for the delayed response. I wasn't getting notified of comments on this PR for some reason. I'll try to get it working today, but I am not too familiar with this, so I can't promise anything.

**Comment by caiyue1993** [comment]
Hi @rodericj , I recommend the latter. However, you could add a `WIP` prefix to the new PR title if you prefer the former. 
I'm looking forward to your contribution and I appreciate people like you.

**Pull request closed without merging**
