### PR TITLE
Per object database selection

### PR DESCRIPTION
**Pull request by matadan**
WIP

This ended up with a bigger set of changes than I was aiming for ;). I've moved a lot of code around but tried my best to keep the actual code the same. It needs a good test.

The original SyncEngine API and example should still work. Any data using the old API should still work but I have not put in anything to migrate from a single object scheme to multiple objects. This could be done if necessary.

The new API is via ObjectSyncEngine() as shown in IceCreamExample2.

This also has everything that will be needed to support public databases on a per object basis. That will go in next.

### CODE REVIEW

**Comment by matadan** [comment]
I moved the example into an Examples folder. This might have broken the travis build check :(

**Comment by caiyue1993** [comment]
Man, you've changed too much. I don't know if it's necessary. I'll try my best to review and do my own `feature/multiple-objects` at the same time. 
And as for the example, you could combine the two and don't need another one example project.

**Comment by matadan** [comment]
The changes kind of exploded but the commits are each pretty small. Sorry it just went that way. And it is a WIP so I haven’t finished or tried to consolidate the changes.

I wanted to keep the old example the same until it was complete to keep backwards compatibility.

But both examples work. If we had a test database and a set of tests to test against it, that would be useful.

--
Andrew Eades

**Comment by matadan** [comment]
This can now sync multiple objects over private and public databases.

**Comment by matadan** [comment]
Nothing works today! I need to build a test framework as I'm just getting weird iCloud problems today.

Just having one example does not work as you have to instantiate it with object types in different databases at launch which requires multiple launches with different setups, so I think a more thorough test suite needs to be implemented.

**Comment by ianbradbury-bizzibody** [comment]
Sorry I did not get and time to test in the end.  I did manage to clone your repo and do some basic testing. I will have time later tonight (UK) and tomorrow evening.

**Comment by matadan** [comment]
I got some pretty bad intermittent iCloud problems yesterday after I consildated the examples. So I will reverse my commits until I have something working. Will let you know when I have it back working again.

--
Andrew Eades

**Comment by ianbradbury-bizzibody** [comment]
@matadan - How's it going?   I'm ready for testing when you are.  :)

**Pull request closed without merging**
