### PR TITLE
Pass completion block in SyncEngine.pull

### PR DESCRIPTION
**Pull request by davidrothera**
As `DatabaseManager.fetchChangesInDatabase` supports passing in a completion block which is run once each zone is fetched lets pass that through as an optional void completion block.

This is a no-op for current users as the block is optional and defaults to nil but it means that we can now pass in a block which is only run once the pull is complete.

Whilst we could just simply observe the Realm itself for these changes there is no way to wait for a signal that all of a given batch (cloud pull) is done.

### CODE REVIEW

**Comment by caiyue1993** [comment]
It looks good but please be aware that since this callback https://github.com/caiyue1993/IceCream/blob/d907729e294a43c0631bc67081c5edc2899d5234/IceCream/Classes/PrivateDatabaseManager.swift#L167
will be called multiple times(if there are multiple zones), is it appropriate enough?

**Comment by davidrothera** [comment]
Yeah I did consider that and being called n times (one for each zone) is better than setting up an observer and being called once for every record inserted.

In a perfect world we could amend this to only run the completion after all zones but I'm not sure the need is high enough for that, what are your thoughts @caiyue1993

**Comment by caiyue1993** [comment]
Hi @davidrothera ,

I've completed the completion handler logic and make it right(which means the `completionHandler` should only be called once every time `pull` method was invoked). However the tweaks indeed add some code which looks not that elegant to the code base. I'm in a tangled feeling now 😖

**Comment by caiyue1993** [comment]
Hi @davidrothera I've made the `completionHandler` right in the privateCloudDatabase(which means it will only be called once after all zones fetch successfully). Ready to merge.

**Comment by caiyue1993** [comment]
And I've also add optional error in the `completionHandler` incase anything wrong happens in the fetching process. Check e0b754f670f2c04512485846b9b60fadbbfb7573

**Pull request merged**
