### PR TITLE
update documentation and adjust some access control

### PR DESCRIPTION
**Pull request by Binlogo**
* add `generate_docs.sh`
* TODO:  setup GitHub Pages to deploy and replace the link in README @caiyue1993

### CODE REVIEW

**Comment by Binlogo** [comment]
[Here](https://binlogo.github.io/IceCream/) is the temporary demonstration .

**Comment by caiyue1993** [comment]
Hi @Binlogo , 
Nice catch for the access control and missing comment! As for the documentation, personally I don't like jazzy doc. I'd prefer using the wiki page that GitHub already provides for us and I'll add to it in the future. 
How about tweaking your commit(remove the jazzy doc stuff) and updating this PR?

**Comment by caiyue1993** [comment]
I've tweaked this commit so that it only contains the access control changes. Still thanks for the contribution!

**Comment by Binlogo** [comment]
Hope it may help. By complete the doc, I read the source code and learn a lot. This is a cool and useful library, I think it worth to go further.

As I know, jazzy doc is convenient and well layout, can integrate with other tool such as Dash. Many popular library is using it, especially for Realm, as jazzy is developed by them. 

I can understand your consideration, maybe using GitHub Action to deploy the doc on the separate `gh-pages` branch could keep the balance.

A friendly accessible doc is vital for a good lib like this. 

Have a nice holiday day.

**Comment by caiyue1993** [comment]
Really appreciate for these kind words! Let's make IceCream better together and wish you a nice holiday as well 😊

**Pull request merged**
