### PR TITLE
Public database working

### PR DESCRIPTION
**Pull request by matadan**
This version appears to be working...
 
Tell SyncEngine to use public database:

`let syncEngine = SyncEngine<MyObject>(usePublicDatabase: true)
`

Mark objects to be stored in public database:

`extension MyObject: StoredInPublicDatabase {}
`

### CODE REVIEW

**Comment by caiyue1993** [comment]
Hi @matadan , thanks for your contribution. And the pr looks great!

And just one question, have you done your test yet? And btw, could you provide some example code?

**Comment by matadan** [comment]
I have it working in an app I’m developing. I can make an example to show how it works. However, I was just wondering whether I should take a slightly different approach...

I would also like multiple objects and have looked at @janandre 's pr (#25). So my suggestion is to combine the 2. And maybe add in shared database whilst I'm there.

SyncEngine() could take an array as you suggested and each object could be flagged as being stored in the private, public or shared database using a property. Then SyncEngine would sync on the requested database depending on the object rather than sync all objects on private or public as in my pr.

I will have to change the zoneID code. Is it there to prevent syncing of non-realm records? Maybe I could use a specific container instead of zones? Or use the existence of the database property on each record/object to tell SyncEngine that it is synced. What do you think?

**Comment by caiyue1993** [comment]
@matadan Yes, I think we should combine the 2 to support all three types of database(public, private and shared). 

> Is it there to prevent syncing of non-realm records? 

Could you explain this more in detail?

> Maybe I could use a specific container instead of zones? Or use the existence of the database property on each record/object to tell SyncEngine that it is synced. 

I prefer to use the default container since we could create custom zones. And since I am not perfectly clear about public/shared database, a further study is required.

And by the way, so in your app, does everyone have the power to modify the public database?

**Comment by matadan** [comment]
What are the zones for? I’m guessing that they are there to partition the container into a "synced with realm objects” zone and non-realm objects everywhere else. At the moment the zone is specific to the single realm object that can be synced.

Public databases only have a default zone so you would need another way to differentiate which CKRecords should be synced as realm objects. So I was thinking that a container that only held objects for IceCream would be a better way to partition the data. Then that container is the synced object container. I think you will still be able to use zones on the private database to partition in the same way as is currently working. It will just be in a different container. This would also be useful for different apps that want to share the same container.

The normal default container would exist for non-synced CKRecords, and an IceCream container would hold the private, public, shared data to be synced.

Part of my app’s functionality is to calculate information that would be useful to all users, so it wants to sync the data to all users once it has worked things out for a single user.

**Comment by caiyue1993** [comment]
Custom zones can do more things than the default zone. For the detail you could watch the related WWDC sessions. So there is no partition of realm objects zone and non-realm objects. Don't mess things up :)

**Comment by matadan** [comment]
I think I've seen all the WWDC vids regarding CloudKit. Any in particular that I may have missed? 
I'm asking to ascertain your motivation for creating the zone so I can understand how to work with the code without breaking it. :)

Maybe I do not understand the current features:

- currently supports a single shared Object and creates a specific zone for it in private database?
- PR 25 adds multiple object support by allowing creation of multiple SyncEngines. 1 SyncEngine per Object? Adds multiple zones.

- currently  does not support public or shared databases
- PR 40 shows a way to switch SyncEngine between private and public databases; but this is kind of a global switch so objects are either all public or all private

I'm looking into a way to support multiple Objects with a single SyncEngine instance that can use either the private or the public database. Objects will be marked for storage in private or public when created. So an app could have some objects synced to all users via public and some synced to a user's devices via private.

And I will look into whether supporting shared makes sense after that.

**Comment by matadan** [comment]
No Problem. It's a great bit of code to work on. Thanks for doing it in the first place.

I'm building a new example app and making changes to support the new features so you can have a look and decide whether to incorporate them or not.

Because the public database does not have custom zones we need to use record types so I'll implement them that way in public database and see if we have any problems. Duplicating the record types by having a custom zone per type seems unnecessary to me but I guess I'll find out soon enough.

**Comment by caiyue1993** [comment]
@matadan Yep. The way has become much more clear as we discussed. And just feel free to do your implements of public database. I'll keep watching this pr since it has a rather high priority. 

(And just a warm hint, don't forget to consider the compatibility with the old IceCream user:)

**Comment by matadan** [comment]
I will try to keep the old API exactly the same and just enhance for multiple objects etc...

I've just noticed the Cream class. It stores a realm reference. This doesn't work if accessed from multiple threads. I've found it much less error-prone to always get a new  reference with Realm().

I have made a realm extension that does some of what Cream does for another project:

```
extension Realm {
    static private var main: Realm {
        get {
            let realm = try! Realm()
            return realm
        }
    }
    
    static func transaction(_ block: (Realm) -> Void) {
        let realm = Realm.main
        do {
            try realm.write {
                block(realm)
            }
        } catch(let error) {
            print("\(error)")
        }
    }
 
    static func query(_ block: (Realm) -> Void) {
        let realm = Realm.main
        block(realm)
    }
}

```

You can then use code like:

```
Realm.transaction { realm in 
  realm.add(object)
}
```

The other thing Cream does is purge all the 'isDeleted = true' objects. I've added code to purge objects is the syncCloudKitObjects callback but there could still be objects hanging around with this flag if something goes wrong so a clean up is a good idea. I wonder if it should happen when SyncEngine starts though as app termination is not a frequent event in real life.

**Comment by matadan** [comment]
Quite a bit of the groundwork is done. I may not have time to do anything tomorrow (Friday 9th) but if you want to have a look, I've pushed to this branch:

https://github.com/matadan/IceCream/tree/per-object-database-selection

The next step is to take an array of types instead of a single type.

**Comment by caiyue1993** [comment]
Nice work! Actually you could pull a request marked with WIP, which can help us to review your code.

**Comment by caiyue1993** [comment]
And I've also checkout a new branch `feature/multiple-objects` myself, welcome to check it out. I'll do my works on that branch and we could compare each other's codes to make it better.

**Comment by matadan** [comment]
OK. I'll take a look. I think I'm done on the multi-object support now too. Just need to test it a bit more. It ended up being a bigger change around than I anticipated. I'll do a PR when I have checked it over.

**Comment by caiyue1993** [comment]
Migrate to #42 . Close this one.

**Pull request closed without merging**
