### PR TITLE
Fix build on Xcode 12

### PR DESCRIPTION
**Pull request by aehlke**
I had to include a missing class file, and I updated to Xcode's recommended settings (which I haven't reviewed closely, I don't know the full impact of them yet)

### CODE REVIEW

**Comment by caiyue1993** [comment]
Yeah, I don't think the changes are necessary except the `PendingRelationshipsWorker` file.

**Comment by aehlke** [comment]
I was unable to build on Big Sur on an Intel Mac without the other accompanying changes. Unfortunately I don't know how to scope it down to the minimal changes required, nor how to maintain compatibility with Apple Silicon build environments (I had to disable arm64 builds for simulator targets to resolve a Carthage build error).

**Comment by aehlke** [comment]
Hmm, this is half-broken. I can't build the project itself from within Xcode 12.4, I get undefined symbol errors from Realm with `ld: symbol(s) not found for architecture arm64`

**Comment by caiyue1993** [comment]
Hi @aehlke, I've raised another pull request to fix Carthage build issue. Simple as that and close this one😆

**Pull request closed without merging**
