### PR TITLE
Multiple objects support

### PR DESCRIPTION
**Pull request by bitomule**
Ok, here comes the big one.

### Why

IceCream needs multiple object support, right now it can only sync one data type.

### How

I´ve changed how SyncEngine works and now we have 2 classes:

- **SyncEngine**: In charge of all the CloudKit login. Manages subscriptions, creation of zones and pushing changes to CloudKit
- **SyncSource**: One for each model you want so sync. They are in charge of the Realm part. They provide required info to SyncEngine and also call SyncEngine when new changes are created in realm so they are pushed to the cloud.

### Result

The only change is setting up the **SyncEngine**. Now it receives all the sources as a parameter.

```
syncEngine = SyncEngine(syncSources: [
      SyncSource<Trip>(),
      SyncSource<Restaurant>()
    ])
```

### Breaking changes

I've used the same **SyncEngine** name but it no longer works as it used to. We can rename the new class and still include the old SyncEngine so old users app keep working without changes or we can pack some more PR and release a big number version.

### Todo in this PR

- [ ] Update readme

### Todo in future

- [ ] Stop using Notification to report changes from CloudKit to the SyncEngine. We should use a method in it that users could call just passing the notification dictionary.
- [ ] Create a new RealmDataSource that feeds the SyncSource
- [ ] Allow that RealmDataSource to write in batches instead of with each change
- [ ] Clean code and add tests

What do you think @caiyue1993 , maybe there's more things to be fixed on this PR.

### CODE REVIEW

**Comment by caiyue1993** [comment]
Hi @bitomule , I don't know whether you're still sticking around.
Recently I'm trying my #45 implementations and I've found it's hard to make `SyncEngine<T: Sequence> where T.Element: Object & CKRecordConvertible & CKRecordRecoverable` work cause we can't pass `SyncEngine<[Dog, Cat]>` in this way. 
So I switch to your implementations and I think yours are much reasonable than mine.

**Comment by bitomule** [comment]
I'm still here! I'm working on a big refactor on my app that includes the CloudKit so I´ll be happy to help :)

**Comment by caiyue1993** [comment]
I'm doing some changes and there are still some work to do. Here is my advices:

- Naming matters. We should keep each name short and to the point. 
- Notification staffs should be upgraded. When content changes in CKRecordZone, we need to know which zone was changed exactly. And now we just traverse each zone and it's not so good.
- Maybe we should avoid using delegate in the code. Personally I dislike the delegation pattern in Swift.
- ...

How do you think of these @bitomule ?  And just ask me if you have any questions on my changes.

**Comment by bitomule** [comment]
@caiyue1993 I don´t have much time to review all the changes but seems good to me. I'm out for the weekend but I´ll pull and try next week.

**Comment by caiyue1993** [comment]
Yeah @bitomule, don't worry. I'll let you know when I finish my changes. I can handle these :)

**Comment by caiyue1993** [comment]
I've updated the demo example and passed some tests in my place. And it is so delightful that these codes keep clean and have no side effects on the old users. 

As for the changes, I use the naming `SyncObject` instead of the `SyncSource`. It's more precise since `SyncObject` is one for each Object model we want to sync.

**Comment by caiyue1993** [comment]
I've done tests on my devices and all actions behave as expected. This pr is ready to be merged.

**Comment by bitomule** [comment]
Amazing work @caiyue1993 !

**Pull request merged**
