### PR TITLE
Add CKAsset support

### PR DESCRIPTION
**Pull request by MrFuFuFu**
This PR is for supporting CKAsset. Including a test demo.

### CODE REVIEW

**Comment by caiyue1993** [comment]
Reference issue #22

**Comment by caiyue1993** [comment]
Thanks for the PR. Checking now. It works in my place and I need to sort the code. 

And a warm prompt: you should checkout a new branch to do your commits. 🙂

**Comment by MrFuFuFu** [comment]
@caiyue1993 Haha, OK, thank you. It's my first PR. I'm not really familiar with that. ^ ^

**Comment by caiyue1993** [comment]
@MrFuFuFu Thanks for  mentioning. I'll check it :)

**Comment by caiyue1993** [comment]
During the review process, I have one question: why we add a separated path value as a property of CKRecord to store in CloudKit? 
Since we already have the CKAsset which integrated `fileURL` property. I think we could just use that.

**Comment by MrFuFuFu** [comment]
Hi @caiyue1993 , as [Apple's doc](https://developer.apple.com/documentation/cloudkit/ckasset/1515050-fileurl) said `Do not expect the name of the file to be the same as the one you used originally to create the asset.` So the url may different, it looks unreliable. 

We need to delete local cache once CKAsset is deleted from another device. Creating a new path value will be more easy to find it in the local cache files. 

And also, Using the same path value with `CreamAsset`'s path can save the local storage, we don't need to have a copy.

Do I get your question?

**Comment by caiyue1993** [comment]
Jesus, I don't know why Apple designs the stuff like that. 

And you're right, obviously.

**Comment by caiyue1993** [comment]
Hi @MrFuFuFu , finally I've made some changes to the codes and you may check it.  

And btw could you please explain to us what does the `removeRedundantCacheFiles(record:)`  do and give a example? I am not perfect clear for now. 

Also, if you have any questions about my code changes, just let me know. :)

**Comment by MrFuFuFu** [comment]
Hi @caiyue1993 , Awesome, Thank you for your changing. It looks very clean and easy to read.

The purpose of `removeRedundantCacheFiles(record:)` is for remove useless cache files. For example, The Realm's Object has many images, e.g. image0, image1, image2.  And the cache file name will be `Object's UUID_image0's UUID` 

image0:

`F0D2D758-8BD5-48D0-8C1F-995EE88A0101_94ACC420-EFD0-4A6D-B953-233680B6E857`

image1:

`F0D2D758-8BD5-48D0-8C1F-995EE88A0101_6EA00FED-22EF-478A-8E42-4F0CAF540C06`

image2:

`F0D2D758-8BD5-48D0-8C1F-995EE88A0101_74DA75DA-FE4F-46CB-8D3E-179827551BE4`

such like that.

Once users set image0 as `nil` in one device, in another device, we should delete this image0's cache files. The cache name should be `F0D2D758-8BD5-48D0-8C1F-995EE88A0101_**********`. This method filter all exist files and then delete not exist files.

**Comment by caiyue1993** [comment]
Roger that. I'll polish a little more and do the final work. And I need to run tests in practice before merging this pr. 👍

**Comment by MrFuFuFu** [comment]
@caiyue1993 Thank you for your hard working. ^ ^. You're really nice.

**Comment by caiyue1993** [comment]
All tests are passed in my side. This pr gonna be merged. And by the way @MrFuFuFu, I temporarily removed the `removeRedundantCacheFiles(record:)` method in the commits because the implementation was so complex and it's not a pressing issue. However, I will add a much cleaner way to solve this in the future. Hope you could understand. :)

If you are facing any problems just let me know.

**Comment by caiyue1993** [comment]
The redundant files removal process has been successfully implemented in #32 .

**Pull request merged**
