### PR TITLE
Realm data source

### PR DESCRIPTION
**Pull request by bitomule**
I've found that the default way to create subscriptions don't work on my case but the commented out Apple way worked.

### What didn't work

When many objects change realm do lots of write operations.

### What have I changed

Created a way to queue realm write operations that would be performed a fixed time after the last operation is added to the queue.

### What did I break

Not sure what this could break. I've tested myself but I thing we need some tests added to the whole library. I´ll try to create a target adding unit tests and making the library more testable.

### CODE REVIEW

**Comment by caiyue1993** [comment]
Yeah, I think the data source idea is great and really inspired me. My original thought was passing an `[T]` which is Sequence type and its `T` meets the old requirements. I am still trying and I need time to review your implementations.

**Comment by bitomule** [comment]
I think having a separate DataSource is great but now I´ll try to focus on adding multiple objects support (I'm working on the PR right now) and then we can split a bit more all the code, add tests... Thanks for your amazing work.

**Comment by caiyue1993** [comment]
So should we focus on your latest #55 and close this one? Or keep both open?

**Comment by bitomule** [comment]
Yep, focus on the multi object one by now and we can go back later.

**Pull request closed without merging**
